# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d27447770a3c4c4ca62dee7f392f65beed80c657a967e45fb19997831df6c417e7cbb68227632c82bd7505a523261399e04067fc7ef01651065fc68fa86429ab

test:
  secret_key_base: 713e9e76f92cc40ad1b5b752287f0dc59c1cb00f6566253abaa09c1f55d45a7f2f5e386ab8b673f9b4ffff68883187622f66fbfa11900dfb484ef09e46dcc387

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
